import { AnalysisResult, Report } from "@/types"
import { formatTimestamp } from "./utils"
import prisma from "./db"

export async function createReport(
  analysis: AnalysisResult,
  includeMessage: boolean = true
): Promise<string> {
  const report = await prisma.report.create({
    data: {
      analysisId: analysis.analysisId,
      shareSlug: analysis.reportId,
      includeMessage,
      title: `PhishShield Report - ${analysis.verdict.toUpperCase()}`,
      status: 'active'
    }
  })
  
  return report.shareSlug
}

export async function getReport(reportId: string): Promise<Report | null> {
  const report = await prisma.report.findUnique({
    where: { shareSlug: reportId },
    include: {
      analysis: {
        include: {
          reasons: true
        }
      }
    }
  })
  
  if (!report) return null
  
  const analysis = report.analysis
  
  return {
    reportId: report.shareSlug,
    createdAt: analysis.createdAt.toISOString(),
    messageText: report.includeMessage ? analysis.inputText : '[Message content hidden]',
    sourceType: analysis.sourceType,
    verdict: analysis.verdict,
    riskScore: analysis.riskScore,
    confidence: analysis.confidence,
    summary: analysis.summary,
    reasons: analysis.reasons.map(reason => ({
      category: reason.category,
      title: reason.title,
      detail: reason.detail,
      severity: reason.severity as 'low' | 'medium' | 'high',
      evidence: reason.evidence
    })),
    recommendedActions: JSON.parse(analysis.recommendedActions),
    detectedUrls: JSON.parse(analysis.detectedUrls)
  }
}

export function generateReportSummary(analysis: AnalysisResult): string {
  const timestamp = formatTimestamp(new Date())
  
  return `
PHISHSHIELD AI INCIDENT REPORT
Generated: ${timestamp}

VERDICT: ${analysis.verdict.toUpperCase()}
RISK SCORE: ${analysis.riskScore}/100
CONFIDENCE: ${Math.round(analysis.confidence * 100)}%

SUMMARY:
${analysis.summary}

DETECTED INDICATORS:
${analysis.reasons.map(reason => `• ${reason.title}: ${reason.detail}`).join('\n')}

RECOMMENDED ACTIONS:
${analysis.recommendedActions.map(action => `• ${action}`).join('\n')}

${analysis.detectedUrls.length > 0 ? `
DETECTED URLS:
${analysis.detectedUrls.map(url => `• ${url.url} (${url.risk})`).join('\n')}
` : ''}

Report ID: ${analysis.reportId}
Analysis ID: ${analysis.analysisId}

---
Generated by PhishShield AI v1.0.0
For support: aryancta@gmail.com
  `.trim()
}

export function generatePrintableReport(report: Report): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <title>PhishShield AI Report - ${report.reportId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }
    .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px; }
    .verdict { padding: 15px; border-radius: 8px; font-weight: bold; text-align: center; margin: 20px 0; }
    .verdict.safe { background: #dcfce7; color: #166534; }
    .verdict.suspicious { background: #fef3c7; color: #92400e; }
    .verdict.high_risk { background: #fecaca; color: #991b1b; }
    .section { margin: 30px 0; }
    .reasons li { margin: 10px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <div class="header">
    <h1>PhishShield AI Security Report</h1>
    <p><strong>Report ID:</strong> ${report.reportId}</p>
    <p><strong>Generated:</strong> ${formatTimestamp(report.createdAt)}</p>
  </div>
  
  <div class="verdict ${report.verdict}">
    VERDICT: ${report.verdict.toUpperCase()} - Risk Score: ${report.riskScore}/100
  </div>
  
  <div class="section">
    <h2>Summary</h2>
    <p>${report.summary}</p>
  </div>
  
  <div class="section">
    <h2>Detected Threat Indicators</h2>
    <ul class="reasons">
      ${report.reasons.map(reason => `
        <li>
          <strong>${reason.title}</strong> (${reason.severity})
          <br>${reason.detail}
          <br><em>Evidence: ${reason.evidence}</em>
        </li>
      `).join('')}
    </ul>
  </div>
  
  <div class="section">
    <h2>Recommended Actions</h2>
    <ul>
      ${report.recommendedActions.map(action => `<li>${action}</li>`).join('')}
    </ul>
  </div>
  
  ${report.detectedUrls.length > 0 ? `
  <div class="section">
    <h2>Suspicious Links Found</h2>
    <ul>
      ${report.detectedUrls.map(url => `
        <li>
          <strong>${url.domain}</strong> - Risk: ${url.risk}
          <br><em>${url.notes.join(', ')}</em>
        </li>
      `).join('')}
    </ul>
  </div>
  ` : ''}
  
  <div class="footer">
    <p>This report was generated by PhishShield AI v1.0.0</p>
    <p>For questions or support, contact: aryancta@gmail.com</p>
  </div>
</body>
</html>
  `.trim()
}