"use client"

import { motion } from "framer-motion"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { 
  Shield, 
  AlertTriangle, 
  XCircle, 
  Eye,
  CreditCard,
  Link as LinkIcon,
  Download,
  Copy,
  Share2,
  ExternalLink,
  Calendar,
  Zap,
  CheckCircle
} from "lucide-react"
import { Report, VerdictType } from "@/types"
import { VerdictBadge } from "@/components/verdict-badge"
import { RiskMeter } from "@/components/risk-meter"
import { formatTimestamp, getRiskColor } from "@/lib/utils"
import { cn } from "@/lib/utils"
import { toast } from "sonner"

interface ReportViewProps {
  report: Report
  className?: string
}

const categoryIcons = {
  urgency: AlertTriangle,
  impersonation: Shield,
  payment: CreditCard,
  url: LinkIcon,
  brand_mismatch: Eye,
}

export function ReportView({ report, className }: ReportViewProps) {
  const handleCopyReport = () => {
    const reportText = `
PhishShield AI Security Report
==============================

Report ID: ${report.reportId}
Generated: ${formatTimestamp(report.createdAt)}

VERDICT: ${report.verdict.toUpperCase()}
Risk Score: ${report.riskScore}/100
Confidence: ${Math.round(report.confidence * 100)}%

SUMMARY:
${report.summary}

DETECTED THREATS:
${report.reasons.map(reason => `• ${reason.title}: ${reason.detail}`).join('\n')}

RECOMMENDED ACTIONS:
${report.recommendedActions.map(action => `• ${action}`).join('\n')}

${report.detectedUrls.length > 0 ? `
SUSPICIOUS URLS:
${report.detectedUrls.map(url => `• ${url.domain} (${url.risk})`).join('\n')}
` : ''}

Generated by PhishShield AI
Contact: aryancta@gmail.com
    `.trim()

    navigator.clipboard.writeText(reportText).then(() => {
      toast.success('Report copied to clipboard')
    }).catch(() => {
      toast.error('Failed to copy report')
    })
  }

  const handlePrintReport = () => {
    window.print()
  }

  const handleShareReport = () => {
    if (navigator.share) {
      navigator.share({
        title: `PhishShield AI Report - ${report.verdict.replace('_', ' ')}`,
        text: `Risk Score: ${report.riskScore}/100 - ${report.summary}`,
        url: window.location.href
      }).catch(() => {
        // Fallback to clipboard
        handleCopyReport()
      })
    } else {
      handleCopyReport()
    }
  }

  return (
    <div className={cn("max-w-4xl mx-auto space-y-6", className)}>
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center print:text-left"
      >
        <Card className="p-8 cyber-border print:border-gray-300 print:bg-white">
          <div className="flex flex-col md:flex-row items-center justify-between mb-6">
            <div className="flex items-center space-x-4">
              <div className="p-3 bg-gradient-to-br from-cyan-500/20 to-blue-500/20 rounded-xl border border-cyan-500/30 print:bg-gray-100 print:border-gray-300">
                <Shield className="w-8 h-8 text-cyan-400 print:text-gray-600" />
              </div>
              <div className="text-left">
                <h1 className="text-3xl font-bold text-white print:text-black">
                  PhishShield AI Report
                </h1>
                <p className="text-slate-400 print:text-gray-600">
                  Security Analysis Report
                </p>
              </div>
            </div>
            
            <div className="flex items-center space-x-2 mt-4 md:mt-0">
              <VerdictBadge verdict={report.verdict as VerdictType} size="lg" />
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <div className="text-slate-400 print:text-gray-500">Report ID</div>
              <div className="font-mono text-white print:text-black">
                {report.reportId.slice(0, 12)}...
              </div>
            </div>
            <div>
              <div className="text-slate-400 print:text-gray-500">Generated</div>
              <div className="text-white print:text-black">
                {formatTimestamp(report.createdAt)}
              </div>
            </div>
            <div>
              <div className="text-slate-400 print:text-gray-500">Risk Score</div>
              <div className="text-white print:text-black font-semibold">
                {report.riskScore}/100
              </div>
            </div>
            <div>
              <div className="text-slate-400 print:text-gray-500">Confidence</div>
              <div className="text-white print:text-black font-semibold">
                {Math.round(report.confidence * 100)}%
              </div>
            </div>
          </div>
        </Card>
      </motion.div>

      {/* Risk Assessment */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card className="p-6 cyber-border print:border-gray-300 print:bg-white">
          <h2 className="text-xl font-bold text-white print:text-black mb-6">
            Risk Assessment
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="flex justify-center">
              <RiskMeter score={report.riskScore} size="lg" />
            </div>
            
            <div className="md:col-span-2 space-y-4">
              <div>
                <h3 className="font-semibold text-white print:text-black mb-2">
                  Summary
                </h3>
                <p className="text-slate-300 print:text-gray-700 leading-relaxed">
                  {report.summary}
                </p>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="p-3 bg-slate-800/30 print:bg-gray-100 rounded-lg border border-slate-700/50 print:border-gray-300">
                  <div className="text-sm text-slate-400 print:text-gray-500">
                    Threats Detected
                  </div>
                  <div className="text-lg font-semibold text-white print:text-black">
                    {report.reasons.length}
                  </div>
                </div>
                
                <div className="p-3 bg-slate-800/30 print:bg-gray-100 rounded-lg border border-slate-700/50 print:border-gray-300">
                  <div className="text-sm text-slate-400 print:text-gray-500">
                    URLs Analyzed
                  </div>
                  <div className="text-lg font-semibold text-white print:text-black">
                    {report.detectedUrls.length}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Card>
      </motion.div>

      {/* Detected Threats */}
      {report.reasons.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card className="p-6 cyber-border print:border-gray-300 print:bg-white">
            <h2 className="text-xl font-bold text-white print:text-black mb-6">
              Detected Threat Indicators
            </h2>
            
            <div className="space-y-4">
              {report.reasons.map((reason, index) => {
                const Icon = categoryIcons[reason.category as keyof typeof categoryIcons] || AlertTriangle
                
                return (
                  <div
                    key={index}
                    className="p-4 bg-slate-800/30 print:bg-gray-50 rounded-lg border border-slate-700/50 print:border-gray-200"
                  >
                    <div className="flex items-start space-x-4">
                      <div className={cn(
                        "p-2 rounded-lg border flex-shrink-0",
                        reason.severity === 'high' 
                          ? 'bg-red-500/10 border-red-500/20 print:bg-red-50 print:border-red-200'
                          : reason.severity === 'medium'
                          ? 'bg-amber-500/10 border-amber-500/20 print:bg-yellow-50 print:border-yellow-200'
                          : 'bg-emerald-500/10 border-emerald-500/20 print:bg-green-50 print:border-green-200'
                      )}>
                        <Icon className={cn(
                          "w-4 h-4",
                          reason.severity === 'high' 
                            ? 'text-red-400 print:text-red-600'
                            : reason.severity === 'medium'
                            ? 'text-amber-400 print:text-yellow-600'
                            : 'text-emerald-400 print:text-green-600'
                        )} />
                      </div>
                      
                      <div className="flex-1">
                        <div className="flex items-center space-x-2 mb-2">
                          <h3 className="font-semibold text-white print:text-black">
                            {reason.title}
                          </h3>
                          <Badge 
                            variant="outline" 
                            className={cn(
                              "text-xs",
                              reason.severity === 'high' 
                                ? 'text-red-400 border-red-500/20 print:text-red-600 print:border-red-300'
                                : reason.severity === 'medium'
                                ? 'text-amber-400 border-amber-500/20 print:text-yellow-600 print:border-yellow-300'
                                : 'text-emerald-400 border-emerald-500/20 print:text-green-600 print:border-green-300'
                            )}
                          >
                            {reason.severity.toUpperCase()}
                          </Badge>
                        </div>
                        
                        <p className="text-slate-300 print:text-gray-700 mb-3 leading-relaxed">
                          {reason.detail}
                        </p>
                        
                        {reason.evidence && (
                          <div className="bg-slate-900/50 print:bg-gray-100 rounded p-3 border border-slate-600/50 print:border-gray-300">
                            <div className="text-xs font-medium text-slate-400 print:text-gray-500 mb-1">
                              Evidence:
                            </div>
                            <code className="text-sm text-cyan-300 print:text-gray-800 font-mono break-all">
                              {reason.evidence}
                            </code>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </Card>
        </motion.div>
      )}

      {/* URL Analysis */}
      {report.detectedUrls.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Card className="p-6 cyber-border print:border-gray-300 print:bg-white">
            <h2 className="text-xl font-bold text-white print:text-black mb-6">
              URL Analysis Results
            </h2>
            
            <div className="space-y-4">
              {report.detectedUrls.map((url, index) => (
                <div
                  key={index}
                  className="p-4 bg-slate-800/30 print:bg-gray-50 rounded-lg border border-slate-700/50 print:border-gray-200"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1 min-w-0">
                      <div className="font-semibold text-white print:text-black truncate">
                        {url.domain}
                      </div>
                      <div className="text-sm text-slate-400 print:text-gray-500 truncate">
                        {url.url}
                      </div>
                    </div>
                    <Badge
                      variant="outline"
                      className={cn(
                        "ml-3 flex-shrink-0",
                        url.risk === 'high_risk'
                          ? 'text-red-400 border-red-500/20 print:text-red-600 print:border-red-300'
                          : url.risk === 'suspicious'
                          ? 'text-amber-400 border-amber-500/20 print:text-yellow-600 print:border-yellow-300'
                          : 'text-emerald-400 border-emerald-500/20 print:text-green-600 print:border-green-300'
                      )}
                    >
                      {url.risk.replace('_', ' ').toUpperCase()}
                    </Badge>
                  </div>
                  
                  {url.notes.length > 0 && (
                    <div className="space-y-1">
                      {url.notes.map((note, noteIndex) => (
                        <div key={noteIndex} className="flex items-start space-x-2 text-sm">
                          <div className="w-1 h-1 bg-slate-500 print:bg-gray-400 rounded-full mt-2 flex-shrink-0" />
                          <span className="text-slate-400 print:text-gray-600">{note}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </Card>
        </motion.div>
      )}

      {/* Recommended Actions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        <Card className="p-6 cyber-border print:border-gray-300 print:bg-white">
          <h2 className="text-xl font-bold text-white print:text-black mb-6">
            Recommended Actions
          </h2>
          
          <div className="space-y-3">
            {report.recommendedActions.map((action, index) => (
              <div
                key={index}
                className="flex items-start space-x-3 p-3 bg-slate-800/30 print:bg-gray-50 rounded-lg border border-slate-700/50 print:border-gray-200"
              >
                <div className="w-6 h-6 rounded-full bg-cyan-500/20 print:bg-blue-100 text-cyan-400 print:text-blue-600 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-sm font-bold">{index + 1}</span>
                </div>
                <span className="text-slate-200 print:text-gray-800 leading-relaxed">
                  {action}
                </span>
              </div>
            ))}
          </div>
        </Card>
      </motion.div>

      {/* Actions Bar */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        className="flex flex-wrap gap-3 no-print"
      >
        <Button
          onClick={handlePrintReport}
          className="bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white"
        >
          <Download className="w-4 h-4 mr-2" />
          Print Report
        </Button>
        
        <Button
          onClick={handleCopyReport}
          variant="outline"
          className="border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          <Copy className="w-4 h-4 mr-2" />
          Copy Text
        </Button>
        
        <Button
          onClick={handleShareReport}
          variant="outline"
          className="border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          <Share2 className="w-4 h-4 mr-2" />
          Share Report
        </Button>
        
        <Button
          onClick={() => window.open('/scan', '_blank')}
          variant="outline"
          className="border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          <ExternalLink className="w-4 h-4 mr-2" />
          New Analysis
        </Button>
      </motion.div>

      {/* Footer */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
        className="text-center py-8 print:py-4"
      >
        <div className="text-sm text-slate-500 print:text-gray-500">
          <p>This report was generated by PhishShield AI v1.0.0</p>
          <p className="mt-1">
            For questions or support, contact:{' '}
            <a href="mailto:aryancta@gmail.com" className="text-cyan-400 print:text-blue-600">
              aryancta@gmail.com
            </a>
          </p>
        </div>
      </motion.div>
    </div>
  )
}